name = "links"
type = "javascript"
account_id = "a0574295ac148c420d69da8c3420a618"
workers_dev = true

[site]
bucket = "./public"
entry-point = "./worker"

[build]
command = "pnpm build:worker-webpack"

[build.upload]
format = "service-worker"
