name = "links"
type = "javascript"
account_id = "a0574295ac148c420d69da8c3420a618"
workers_dev = true

[site]
bucket = "./public"
entry-point = "./site"

[build]
upload.format = "service-worker"
command = "yarn build"
