name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn fmt:check
      - run: yarn build
      - run: yarn deploy
        if: github.ref == 'refs/heads/main'
        env:
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          FEEDBIN_API_KEY: ${{ secrets.FEEDBIN_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
