name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: '14'
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.4.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm fmt:check
      - run: pnpm build
        env:
          FEEDBIN_API_KEY: ${{ secrets.FEEDBIN_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      - run: pnpm deploy
        if: github.ref == 'refs/heads/main'
        env:
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          FEEDBIN_API_KEY: ${{ secrets.FEEDBIN_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
