name: Deploy
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn fmt:check
      - run: yarn deploy
        env:
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          FEEDBIN_API_KEY: ${{ secrets.FEEDBIN_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
